spring:
  application:
    name: jpah2

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # In-memory H2 DB ??
    driver-class-name: org.h2.Driver
    username: sa  # ?? ???
    password:  # ?? ????
    hikari:
      pool-name: HikariCP  # HikariCP ?? ? ??
  h2:
    console:
      enabled: true  # H2 ?? ??? (????)
      path: /h2-console  # H2 ?? URL ??
  jpa:
    hibernate:
      ddl-auto: update  # JPA DDL ?? ?? ? ????  create, update... etc
    show-sql: true  # ???? SQL? ??? ??
    database-platform: org.hibernate.dialect.H2Dialect  # H2 DB? Hibernate Dialect ??