spring:
  application:
    name: jpah2

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # In-memory H2 DB
    driver-class-name: org.h2.Driver
    username: sa  # root
    password:  # inital pw is not exist
    hikari:
      pool-name: HikariCP  # HikariCP
  h2:
    console:
      enabled: true  # H2 log use : true
      path: /h2-console  #
  jpa:
    hibernate:
      ddl-auto: create  # JPA DDL option :   create, update... etc
    show-sql: true  # show sql query : true
    database-platform: org.hibernate.dialect.H2Dialect  # H2 DB Hibernate Dialect : jpa dialect target is h2 db